name: Integration Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TESTBOT_TOKEN: ${{ secrets.TELEGRAM_TESTBOT_TOKEN }}
      TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_REPLY_TO_MESSAGE_ID: ${{ secrets.TELEGRAM_REPLY_TO_MESSAGE_ID }}
      TELEGRAM_SUPERGROUP_CHAT_ID: ${{ secrets.TELEGRAM_SUPERGROUP_CHAT_ID }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -coverprofile=coverage.out -covermode=atomic -v tests/.

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
